#!/bin/bash

TAGCOMMAND="computeronix/gunbot:latest --push"
PLATFORM="linux/amd64" #linux/arm64

docker buildx create --name builder --driver docker-container --bootstrap --use

docker buildx build \
    --platform=${PLATFORM} \
    -f "${DOCKERFILE_PATH}" \
    -t "${TAGCOMMAND}" .
