#!/bin/bash

STABLEVERSION=$(curl https://gunthy.trade/tag)
IMAGENAME="gunbot"
TAGNAME="stable-${STABLEVERSION}"
DOCKERLABEL="${IMAGENAME}:${TAGNAME}"

docker tag $DOCKERLABEL $DOCKER_REPO:$TAGNAME
docker push $DOCKER_REPO:$TAGNAME
