name: Cascading Merge
on:
  push:
    branches:
      - master
      - stable
      - beta

jobs:
  cascading-merge:
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      - name: Cascading Merge
        uses: mheap/cascading-merge-action@v1
        with:
          # Changes to `branch-1` will automatically be merged into `branch-2` and `branch-3`
          branches: |
            master
            stable
            beta
